## Default login is admin admin
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - ~/freedomlab:/srv/Files # Expose docker stack files
      - /media/jpeyton/Storage:/srv/Storage # Volume for additional drive
      - /media/jpeyton/HubStorage:/srv/HubStorage # Volume for additional drive
      - ./config/settings.json:/config/settings.json # Filebrowser settings
      - ./config/healthcheck.sh:/healthcheck.sh
      - ~/freedomlab/data/filebrowser/filebrowser.db:/database/filebrowser.db # DB for storage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 8908:80 #Change the port if needed
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: ${NETWORK_PROXY}
