## Default login is admin admin
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /home/jpeyton/portainer:/srv/Files #Change to match your directory
      - /media/jpeyton/HubStorage:/srv/HubStorage
      - /media/jpeyton/Storage:/srv/Storage
      - /home/jpeyton/portainer/FileBrowser/filebrowser.db:/database/filebrowser.db #Change to match your directory
      - /home/jpeyton/portainer/FileBrowser/settings.json:/config/settings.json #Change to match your directory
      - /home/jpeyton/portainer/FileBrowser/healthcheck.sh:/healthcheck.sh
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 8908:80 #Change the port if needed
    networks:
      - proxy

networks:
  proxy:
    external: true
