include:
  # - path: 'docker-compose.networks.yml'
  # - path: 'dockge/docker-compose.yml'
  - path: 'stacks/code-server/docker-compose.yml'
  - path: 'stacks/docker-proxy/docker-compose.yml'
  - path: 'stacks/filebrowser/docker-compose.yml'
  - path: 'stacks/homepage/docker-compose.yml'
  - path: 'stacks/homer/docker-compose.yml'
  - path: 'stacks/mongo/docker-compose.yml'
  - path: 'stacks/mongo-express/docker-compose.yml'
  - path: 'stacks/nginx-proxy-manager/docker-compose.yml'
  - path: 'stacks/ntfy/docker-compose.yml'
  - path: 'stacks/portainer/docker-compose.yml'
  - path: 'stacks/uptime-kuma/docker-compose.yml'
  - path: 'stacks/ntfy/docker-compose.yml'
  - path: 'stacks/watchtower/docker-compose.yml'
