services:
  mongo:
    image: mongo:7
    container_name: mongo
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: ${NETWORK_PROXY}