services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    environment:
      # ME_CONFIG_MONGODB_URL: mongodb://mongodb.freedomlab.xyz
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      # ME_CONFIG_SITE_SESSIONSECRET: secret
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8905:8081
    networks:
      - proxy
    depends_on:
      - mongo

networks:
  proxy:
    external: true
    name: ${NETWORK_PROXY}