services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - ./config:/www/assets # Make sure your local config directory exists
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
      - UID=${PUID:-1000}
      - GID=${PGID:-1000}
    ports:
      - 8902:8080
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: ${NETWORK_PROXY}
