services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /home/jpeyton/portainer/Homepage/config:/app/config # Make sure your local config directory exists
      - /home/jpeyton/portainer/Homepage/config/icons:/app/public/icons
      - /media/jpeyton/HubStorage:/media/HubStorage # Volume for additional drive
      - /media/jpeyton/Storage:/media/Storage # Volume for additional drive
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 8903:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
