services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-America/New_York}
      - WATCHTOWER_SCHEDULE=0 0 0 * * 1
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_DISCORD}
    networks:
      - admin

networks:
  admin:
    external: true
    name: ${NETWORK_ADMIN}