services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TIMEZONE:-America/New_York}
      - WATCHTOWER_SCHEDULE=0 0 0 * * 1
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATION_URL=discord://PFmkkoj7KO2xDfYrjVSWJPFlRInmCUT3ItQKsE-EZjKrdBfpWnbmFKJI2PwJQApgtXk1@1156746023268532234?Username=Watchtower
    networks:
      - proxy

networks:
  proxy:
    external: true