services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - 8907:3001
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: ${NETWORK_PROXY}
