services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    volumes:
      - .~/freedomlab/data/nginx-proxy-manager:/config
    environment:
      - USER_ID=${PUID:-1000}
      - GROUP_ID=${PGID:-1000}
    ports:
      - 443:4443
      - 80:8080
      - 81:8181
    networks:
      - proxy
      - admin

networks:
  proxy:
    external: true
    name: ${NETWORK_PROXY}
  admin:
    external: true
    name: ${NETWORK_ADMIN}