services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jpeyton/dockge/data:/app/data
      # Stacks Directory
      - /home/jpeyton/stacks:/home/jpeyton/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/jpeyton/stacks
    networks:
      - proxy

networks:
  proxy:
    external: true